import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useTranslation from "next-translate/useTranslation";
import { SliderHome } from "../components/slider";
import  wallpaper  from "../public/assets/images/wallpaper.png";
import React,{useEffect,useState} from 'react';
 
export default function Home() {
  let { t } = useTranslation("common");
  const [ mounted, setMounted ] = useState(false);
   useEffect(() => setMounted(true), []);   // at init only
   
  return mounted?(
    <div className={styles.container}>
      <Head>
      
        <meta name="description" content="Maharah Human Resources" />
        <meta name="author" content="Generated by Zyad Mahmoud 00201060080362" />
        <link rel="icon" href="/favicon.ico" />
        <title>{t("titleـpage")} </title>
      </Head>
      

     <main className={styles.main}>
     <img
     className='logo'
                src={'/assets/images/Logo.png'}
                alt="home"
                />
        <img src={"assets/images/wallpaper.png"} className="img-fluid" />
        
        
       <SliderHome/>
      </main>

     

     
    </div>
  ):null
}
